### **스팸 메일 분류하기**

단어 임베딩 학습 위주로...  
202435119 한여원

In [23]:
import numpy as np
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [24]:
# 데이터 만들기 처음 5개는 광고, 나머지는 아님
docs = ['additional income',
        'best price',
        'big bucks',
        'cash bonus',
        'earn extra cash',
        'spring savings certificate',
        'valero gas marketing',
        'all domestic employees',
        'nominations for oct',
        'confirmation from spinner'
]

labels = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [21]:
# 정수 인코딩하기. 이름은 one_hot이지만 해시를 통해 정수 라벨링이 되어서 나온다
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[35, 33], [20, 40], [45, 3], [17, 31], [14, 33, 17], [20, 49, 26], [13, 2, 1], [42, 40, 33], [26, 14, 38], [25, 28, 29]]


In [22]:
# 패딩 씌우기
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[35 33  0  0]
 [20 40  0  0]
 [45  3  0  0]
 [17 31  0  0]
 [14 33 17  0]
 [20 49 26  0]
 [13  2  1  0]
 [42 40 33  0]
 [26 14 38  0]
 [25 28 29  0]]


In [17]:
# 신경망 구축
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [25]:
model.fit(padded_docs, labels, epochs=50, verbose=0)

# 별로... 의미 없는거 같은데...
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print(f'정확도: {accuracy}')

정확도: 1.0


In [26]:
test_docs = ['big income']
encoded_docs = [one_hot(d, vocab_size) for d in test_docs]
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')

print(model.predict(padded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
[[0.6019835]]


역시나 정확도가 높지 않다.  
데이터가 너무 작아서 그런듯. 그냥 임베딩하는 방식을 이해하자